### ISSUE TITLE
deploy env failed

### ISSUE THREAD

**Issue by Sbolder** [094459/blogpost-cdk-mwaa#5]
Hi,

the command : cdk deploy MWAA-Environment
generate following error:

MWAA-Environment: deploying...

 ❌  MWAA-Environment failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://773637102482/eu-west-2")
    at addMetadataAssetsToManifest (C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\assets.ts:27:11)
    at deployStack (C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\api\deploy-stack.ts:237:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CdkToolkit.deploy (C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\cdk-toolkit.ts:209:24)
    at initCommandLine (C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\cli.ts:342:12)

if i run  cdk bootstrap: the error returned id:

 ⏳  Bootstrapping environment aws://773637102482/eu-west-2...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
CDKToolkit |  0/12 | 12:01:16 PM | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack | CDKToolkit User Initiated
CDKToolkit |  0/12 | 12:01:24 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | CDKToolkit User Initiated
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket       | StagingBucket
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | CloudFormationExecutionRole
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_IN_PROGRESS   | AWS::ECR::Repository  | ContainerAssetsRepository
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | LookupRole
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_IN_PROGRESS   | AWS::SSM::Parameter   | CdkBootstrapVersion
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_FAILED        | AWS::S3::Bucket       | StagingBucket cdk-hnb659fds-assets-773637102482-eu-west-2 already exists
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_FAILED        | AWS::IAM::Role        | CloudFormationExecutionRole Resource creation cancelled
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_FAILED        | AWS::IAM::Role        | LookupRole Resource creation cancelled
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_FAILED        | AWS::IAM::Role        | FilePublishingRole Failed to fetch resource hooks to invoke for the resource
CDKToolkit |  0/12 | 12:01:29 PM | CREATE_FAILED        | AWS::ECR::Repository  | ContainerAssetsRepository Resource creation cancelled
CDKToolkit |  0/12 | 12:01:30 PM | CREATE_FAILED        | AWS::SSM::Parameter   | CdkBootstrapVersion Resource creation cancelled
CDKToolkit |  0/12 | 12:01:30 PM | CREATE_FAILED        | AWS::IAM::Role        | ImagePublishingRole Failed to fetch resource hooks to invoke for the resource
CDKToolkit |  0/12 | 12:01:30 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | CDKToolkit The following resource(s) failed to create: [ImagePublishingRole, FilePublishingRole, CdkBootstrapVersion, LookupRole, StagingBucket, CloudFormationExecutionRole, ContainerAssetsRepository]. Rollback requested by user.
CDKToolkit |  0/12 | 12:01:37 PM | DELETE_SKIPPED       | AWS::S3::Bucket       | StagingBucket
CDKToolkit |  1/12 | 12:01:37 PM | DELETE_COMPLETE      | AWS::IAM::Role        | ImagePublishingRole
CDKToolkit |  2/12 | 12:01:37 PM | DELETE_COMPLETE      | AWS::IAM::Role        | CloudFormationExecutionRole
CDKToolkit |  3/12 | 12:01:37 PM | DELETE_COMPLETE      | AWS::SSM::Parameter   | CdkBootstrapVersion
CDKToolkit |  4/12 | 12:01:37 PM | DELETE_COMPLETE      | AWS::IAM::Role        | FilePublishingRole
CDKToolkit |  5/12 | 12:01:37 PM | DELETE_COMPLETE      | AWS::ECR::Repository  | ContainerAssetsRepository
CDKToolkit |  6/12 | 12:01:37 PM | DELETE_COMPLETE      | AWS::IAM::Role        | LookupRole
CDKToolkit |  7/12 | 12:01:38 PM | ROLLBACK_COMPLETE    | AWS::CloudFormation::Stack | CDKToolkit

Failed resources:
CDKToolkit | 12:01:29 PM | CREATE_FAILED        | AWS::S3::Bucket       | StagingBucket cdk-hnb659fds-assets-773637102482-eu-west-2 already exists
CDKToolkit | 12:01:29 PM | CREATE_FAILED        | AWS::IAM::Role        | FilePublishingRole Failed to fetch resource hooks to invoke for the resource
CDKToolkit | 12:01:30 PM | CREATE_FAILED        | AWS::IAM::Role        | ImagePublishingRole Failed to fetch resource hooks to invoke for the resource
 ❌  Environment aws://773637102482/eu-west-2 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at waitForStackDeploy (C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\api\util\cloudformation.ts:311:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at prepareAndExecuteChangeSet (C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\api\deploy-stack.ts:376:26)
    at C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\cdk-toolkit.ts:575:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\cdk-toolkit.ts:572:5)
    at initCommandLine (C:\ProgramData\nvm\v12.13.1\node_modules\aws-cdk\lib\cli.ts:342:12)

Thanks

**Comment by Sbolder** [comment]
Failed resources:
CDKToolkit | 12:08:11 PM | CREATE_FAILED        | AWS::IAM::Role        | CloudFormationExecutionRole API: iam:AttachRolePolicy User: arn:aws:iam::773637102482:user/d.boldrin is not authorized to perform: iam:AttachRolePolicy on resource: role cdk-hnb659fds-cfn-exec-role-773637102482-eu-west-2 with an explicit deny

**Comment by 094459** [comment]
Which version of cdk are you using (cdk --version)?

**Comment by Sbolder** [comment]
PS C:\_demo\blogpost-airflow-hybrid\cdk\mwaa-cdk>  cdk --version
2.20.0 (build 738ef49)

**Comment by 094459** [comment]
The user you are deploying this as (d.boldrin), have you checked the permissions this user has vs what the cdk bootstrap process needs. I found [this page in the docs](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) that shows the differences between cdk v1 and v2 with regards to the permissions needed. Whilst I have never tried this, "cdk bootstrap" allows you to change the IAM Role used by using the "--cloudformation-execution-policies" command line option, so this might be worth trying.

**Comment by 094459** [comment]
Also, there is this [blog post](https://medium.com/@imageryan/bootstrapping-aws-cdk-in-a-secure-environment-9bc778ea6d94) which may also help.

**Comment by Sbolder** [comment]
i have solved with cdk version:

PS C:\_demo\blogpost-airflow-hybrid\cdk\mwaa-cdk> cdk --version
1.152.0 (build 9487b39)

**Comment by 094459** [comment]
If I get the time I will try and reproduce this. I currently use cdk version 2.0.0 (build 4b6ce31), but I had my CDK bootstrapped before I upgraded, so maybe that is why I did not see this error.

**Comment by Sbolder** [comment]
Ok, thanky you very much Ric. 
I have followed your spech at QconLondon and now i want reproduce in our company to create a new business.

I write an email to you, if have some minute for me.

Thank you

**Comment by 094459** [comment]
Yeah, keep me posted in how you get on.
